### ISSUE TITLE
Update XLGM Discord Checklist

### ISSUE THREAD

**Issue by redgouf** [MCBTay/XLGearModifier#176]
Update main live Discord for XLGM2 Checklist.

- [x] Clear Roles from all users
- [x] Purge old members
- [x] Update #Rules
- [x] Update #FAQ
- [x] Update #Download (previously #xl-gear-modifier)
- [x] Update #XL-Gear-Resources
- [x] Remove #Official-Texture-Releases; this will be condensed down into to #Official-Asset-Releases
- [x] NEW SECTION: `XLGM v1.5 Section`
- [x] Archive #Official-Asset-Releases to `XLGM v1.5 Section`
- [x] Update Newest XLGM 2.0 Release Channels
- [x] Clean XLGM 2.0 Release Channels of test data
- [x] CarlBot - Setup new 'react' role for role = `Asset Posting Template Verified`

- [x] Archive all old #mesh and #texture channels to  `XLGM v1.5` section
- [x] Delete #Holiday channels

- [x] Post **RELEASE EVENT** and post in #announcements
